INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:15:48] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:15:48] "GET /static/css/main.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:15:50] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:16:15] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:16:16] "GET / HTTP/1.1" 200 -
INFO:app:Healthz request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:16:20] "GET /healthz HTTP/1.1" 200 -
INFO:app:Metrics request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:16:26] "GET /metrics HTTP/1.1" 200 -
INFO:app:About request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:17:24] "GET /about HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:17:30] "GET /notfound HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:17:44] "GET /404 HTTP/1.1" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:31:55] "GET / HTTP/1.1" 200 -
INFO:app:About Us request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:31:58] "GET /about HTTP/1.1" 200 -
INFO:app:Article created successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:32:00] "GET /create HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:32:08] "POST /create HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:32:08] "GET / HTTP/1.1" 200 -
INFO:app:Article request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:32:12] "GET /7 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:33:32] "GET / HTTP/1.1" 200 -
INFO:app:Article request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:33:34] "GET /1 HTTP/1.1" 200 -
INFO:app:About Us request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:33:36] "GET /about HTTP/1.1" 200 -
INFO:app:Article created successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:33:38] "GET /create HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:33:44] "POST /create HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:33:44] "GET / HTTP/1.1" 200 -
INFO:app:Article does not exist
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:33:55] "GET /404 HTTP/1.1" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:45:46] "GET / HTTP/1.1" 200 -
INFO:app:Article is retrieved.
INFO:app:Article request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:45:48] "GET /1 HTTP/1.1" 200 -
INFO:app:About Us request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:45:51] "GET /about HTTP/1.1" 200 -
INFO:app:Article created successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:45:53] "GET /create HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:45:59] "POST /create HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:45:59] "GET / HTTP/1.1" 200 -
INFO:app:Article is retrieved.
INFO:app:Article does not exist
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 13:46:03] "GET /404 HTTP/1.1" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:07:14] "GET / HTTP/1.1" 200 -
INFO:app:{'Article {post_id} retrieved!'}
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:07:15] "GET /1 HTTP/1.1" 200 -
INFO:app:About Us request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:07:18] "GET /about HTTP/1.1" 200 -
INFO:app:{'Article {title} created!'}
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:07:19] "GET /create HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:07:35] "POST /create HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:07:35] "GET / HTTP/1.1" 200 -
INFO:app:{'Article {post_id} retrieved!'}
INFO:app:Article does not exist
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:07:42] "GET /404 HTTP/1.1" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:09:42] "GET / HTTP/1.1" 200 -
INFO:app:{'Article (post_id) retrieved!'}
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:09:42] "GET /1 HTTP/1.1" 200 -
INFO:app:About Us request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:09:44] "GET /about HTTP/1.1" 200 -
INFO:app:{'Article (title) created!'}
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:09:45] "GET /create HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:09:52] "POST /create HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:09:52] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:21:14] "GET / HTTP/1.1" 200 -
INFO:app:Article ${post_id} retrieved!
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:21:18] "GET /1 HTTP/1.1" 200 -
INFO:app:About us request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:21:19] "GET /about HTTP/1.1" 200 -
INFO:app:Article ${title} created!
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:21:20] "GET /create HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:21:33] "POST /create HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:21:33] "GET / HTTP/1.1" 200 -
INFO:app:Article ${post_id} retrieved!
INFO:app:Article does not exist
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:21:37] "GET /404 HTTP/1.1" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:25:36] "GET / HTTP/1.1" 200 -
INFO:app:Article 1 retrieved!
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:25:38] "GET /1 HTTP/1.1" 200 -
INFO:app:About us request successfull
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:25:39] "GET /about HTTP/1.1" 200 -
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/julianafogg/Desktop/nd064_course_1/project/techtrends/app.py", line 111, in create
    app.logger.info(f'Article {title} created!')
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:25:41] "GET /create HTTP/1.1" 500 -
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/julianafogg/Desktop/nd064_course_1/project/techtrends/app.py", line 111, in create
    app.logger.info(f'Article {title} created!')
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:25:46] "GET /create HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:39:33] "GET / HTTP/1.1" 200 -
INFO:app:Article 1 retrieved!
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:39:35] "GET /1 HTTP/1.1" 200 -
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/julianafogg/Desktop/nd064_course_1/project/techtrends/app.py", line 111, in create
    app.logger.info('%s Article created', title)
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:39:38] "GET /create HTTP/1.1" 500 -
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/julianafogg/Desktop/nd064_course_1/project/techtrends/app.py", line 111, in create
    # app.logger.info('%s Article created', title)
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:39:51] "GET /create HTTP/1.1" 500 -
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/julianafogg/Desktop/nd064_course_1/project/techtrends/app.py", line 111, in create
    # app.logger.info('%s Article created', title)
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:39:52] "GET /create HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:39:55] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/julianafogg/Desktop/nd064_course_1/project/techtrends/app.py", line 111, in create
    # app.logger.info('%s Article created', title)
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:39:56] "GET /create HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:43:14] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:43:16] "GET /create HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/julianafogg/Desktop/nd064_course_1/project/techtrends/app.py", line 111, in create
    app.logger.info('%s Article created', title)
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 14:43:51] "GET /create HTTP/1.1" 500 -
